spring:
  application:
    name: Ribbon-Client

helloworld:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:8091,localhost:8092
    ServerListRefreshInterval: 1000

server:
  port: 8089